name: "Hello World workflow"
on:
  push: 
    branches:
      - master
      - production
jobs:
  Hello-World:
    runs-on: ubuntu-latest
    steps:
      - name: "Print Hello-World"
        run: echo "Hello world"

      - name: "OS information"
        run: cat /etc/os-release